---
info:
  title: Mybff
  description: myBFF - a Brute Force Framework
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/myBFF
  x-cortex-tag: mybff
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: pentesting
  x-cortex-groups:
  - exposure:internal-ship
openapi: 3.0.1
servers:
- url: "/"
